ci: disable cram tests on Windows
cram adds an environment variable called TESTSHELL to each test.
Unfortunately, the value is encoded with fsencode, which produces a bytes
object on Windows, but Python on Windows does not support non-string
environment:

'TESTSHELL': b'C:\\Program Files\\Git\\usr\\bin\\sh.EXE

File "C:\Python\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
TypeError: environment can only contain strings

This commit disables cram tests until the env problem is fixed.